# Generated by Django 5.1.2 on 2025-04-24 05:37

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UZ', unique=True)),
                ('website', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='graduates/images/')),
                ('birth_date', models.DateField()),
                ('education_form', models.CharField(choices=[('day', 'Kunduzgi'), ('evening', 'Kechki'), ('external', 'Sirtqi'), ('distance', 'Masofaviy ta’lim')], default='day', max_length=50)),
                ('academic_score', models.FloatField(default=0.0)),
                ('enrollment_year', models.DateField()),
                ('completed_year', models.DateField()),
                ('status', models.CharField(choices=[('active', "O'qiyapti"), ('graduated', 'Bitirgan'), ('expelled', 'Haydalgan')], default='graduated', max_length=50)),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumni.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('stage', models.FloatField(default=0.5)),
                ('salary', models.FloatField(default=0)),
                ('start_date', models.DateField()),
                ('employment_type', models.CharField(choices=[('full_time', 'To‘liq stavka'), ('part_time', 'Yarim stavka'), ('internship', 'Amaliyot'), ('freelance', 'Freelans (mustaqil)')], default='part_time', max_length=50)),
                ('is_current_employed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.company')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.graduate')),
            ],
        ),
        migrations.CreateModel(
            name='GraduateContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UZ', unique=True)),
                ('linkedin', models.URLField()),
                ('telegram', models.URLField()),
                ('graduate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumni.graduate')),
            ],
        ),
    ]
