# Generated by Django 5.1.2 on 2025-05-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('sum_number', models.IntegerField(default=0)),
                ('self_field', models.IntegerField(default=0)),
            ],
        ),
    ]
