# Generated by Django 5.1.2 on 2025-05-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='year',
            field=models.IntegerField(),
        ),
    ]
